type Props = { t: (id: string, en: string) => string };

export function GuideContent({ t }: Props) {
  return <div className="guide-content">
    <p>{t('The Minds adalah permainan kartu kooperatif untuk 2–4 pemain. Kalian menang atau kalah sebagai satu tim. Tantangannya: memainkan kartu dari kecil ke besar tanpa mengetahui isi tangan teman.', 'The Minds is a cooperative card game for 2–4 players. You win or lose as one team. The challenge is to play cards from lowest to highest without knowing your friends’ hands.')}</p>
    <p className="guide-callout">{t('Tidak ada giliran. Jangan membocorkan angka kartu, memberi kode, atau menyepakati hitungan waktu. Setiap pemain hanya boleh memainkan kartu terendah di tangannya.', 'There are no turns. Do not reveal card numbers, send coded signals, or agree on a timed counting system. Each player can only play their lowest remaining card.')}</p>
    <p>{t('Buka bagian yang ingin kamu pelajari. Semua contoh di bawah adalah ilustrasi; bukan kartu dari room yang sedang dimainkan.', 'Open any section to read more. All examples below are illustrations, not cards from your current room.')}</p>

    <details open><summary>{t('1. Mulai dari room sampai kartu dibagikan', '1. From joining a room to getting your cards')}</summary>
      <ol>
        <li>{t('Masukkan nama panggilan. Tidak perlu membuat akun. Nama harus berbeda dari peserta lain dalam room, termasuk perbedaan huruf besar/kecil: Budi dan budi dianggap sama.', 'Enter a nickname. No account is required. Names must be unique within a room, ignoring letter case: Budi and budi are the same name.')}</li>
        <li>{t('Buat room atau masukkan kode undangan. Pembuat room menjadi host dan pemain pertama. Host dapat menyalin tautan untuk mengundang teman.', 'Create a room or enter an invitation code. The creator becomes the host and first player. The host can copy the room link to invite friends.')}</li>
        <li>{t('Pemain yang masuk sebelum permainan dimulai mengisi kursi kosong, hingga empat pemain. Jika permainan sudah berjalan atau kursi penuh, peserta baru menjadi penonton selama kapasitas penonton tersedia.', 'People joining before the game begins take an available seat, up to four players. If play has started or all seats are taken, newcomers become spectators if spectator capacity allows.')}</li>
        <li>{t('Host membuka “Pemain & pengaturan room” jika ingin mengatur perilaku saat koneksi terputus. Setelah 2–4 pemain terhubung, host menekan “Bagikan kartu”. Tidak ada tombol Siap di lobi.', 'The host can open “Players & room settings” to configure disconnect behavior. Once 2–4 players are connected, the host presses “Deal cards”. There is no Ready button in the lobby.')}</li>
        <li>{t('Lihat kartu sendiri, lalu tekan “Aku siap”. Jika belum semua siap, kamu boleh menekan “Batal siap”. Permainan aktif segera setelah seluruh pemain online siap, tanpa hitung mundur.', 'Look at your cards, then press “I’m ready”. While waiting for others, you can press “Cancel ready”. Play begins as soon as all online players are ready, without a countdown.')}</li>
      </ol>
    </details>

    <details><summary>{t('2. Level, pembagian kartu, dan tujuan tim', '2. Levels, dealing, and your team’s goal')}</summary>
      <p>{t('Dek berisi angka 1–100, masing-masing satu kartu. Pada level N, setiap pemain menerima N kartu. Semua 100 kartu dikocok ulang untuk setiap level baru; angka dari level sebelumnya boleh muncul lagi. Kartu yang tidak dibagikan tidak ikut menentukan urutan level itu.', 'The deck contains one card for every number from 1 to 100. At level N, every player receives N cards. All 100 cards are shuffled again for each new level, so numbers from earlier levels can return. Undealt cards do not count toward that level’s playing order.')}</p>
      <table><caption>{t('Pengaturan awal sesuai jumlah pemain', 'Starting setup by player count')}</caption><thead><tr><th scope="col">{t('Pemain', 'Players')}</th><th scope="col">{t('Nyawa', 'Lives')}</th><th scope="col">Shuriken</th><th scope="col">{t('Target level', 'Final level')}</th></tr></thead><tbody>{[[2,2,1,12],[3,3,1,10],[4,4,1,8]].map(row=><tr key={row[0]}>{row.map((n,i)=><td key={i}>{n}</td>)}</tr>)}</tbody></table>
      <p>{t('Level selesai ketika semua tangan pemain kosong dan tim masih memiliki nyawa. Tim menang setelah menyelesaikan target level; tim kalah jika kehilangan nyawa terakhir, sekalipun kartu terakhir juga sudah habis.', 'A level is complete when all players’ hands are empty and the team still has a life. Complete the final level to win. Losing the last life ends the game in defeat, even if it also clears the final cards.')}</p>
      <div className="guide-example"><h4>{t('Contoh pembagian', 'Dealing example')}</h4><p>{t('Tiga pemain di level 3 mendapat tiga kartu per orang: sembilan kartu total. Hanya sembilan kartu itu yang perlu diselesaikan. Tim tiga pemain harus mencapai akhir level 10 untuk menang.', 'Three players at level 3 receive three cards each: nine in total. Only those nine cards need to be cleared. A three-player team wins by completing level 10.')}</p></div>
    </details>

    <details><summary>{t('3. Membaca meja dan memainkan kartu', '3. Reading the table and playing a card')}</summary>
      <ul>
        <li>{t('Bagian atas menunjukkan level, nyawa bersama, dan shuriken bersama. Token pemain menunjukkan nama, status koneksi/kesiapan, serta jumlah kartu tersisa.', 'The top of the table shows the level, shared lives, and shared shurikens. Player tokens show names, connection/readiness status, and remaining card counts.')}</li>
        <li>{t('Tumpukan tengah memperlihatkan kartu terakhir yang dimainkan. Tidak ada riwayat angka yang bisa dibuka kembali.', 'The center pile shows the last card played. There is no browsable history of previous card numbers.')}</li>
        <li>{t('Bagian “Kartumu” hanya menampilkan tanganmu. Kartu diurutkan kecil ke besar; kartu terendah ditandai dan menjadi satu-satunya kartu yang dapat dimainkan.', '“Your hand” shows only your own cards. They are sorted from lowest to highest; the lowest card is marked and is the only one you can play.')}</li>
        <li>{t('Ketuk atau klik kartu terendah sekali untuk memainkannya. Tidak ada dialog konfirmasi dan kartu tidak bisa ditarik kembali. Kamu boleh memainkan dua kartumu berurutan, tetapi tetap satu per satu.', 'Tap or click your lowest card once to play it. There is no confirmation dialog and no undo. You can play two of your cards in succession, but each must be played separately.')}</li>
        <li>{t('Jika tanganmu sudah kosong, tetaplah bersama tim: kamu masih perlu ikut kesiapan dan voting shuriken. Kamu tidak mendapat kartu pengganti di tengah level.', 'If your hand is empty, stay with the team: you still participate in readiness and shuriken votes. You do not receive replacement cards during a level.')}</li>
      </ul>
      <div className="guide-example"><h4>{t('Contoh urutan benar', 'Correct-order example')}</h4><p>{t('Di level 2, Naya memegang 12 dan 47; Raka memegang 26 dan 80. Urutan yang benar adalah:', 'At level 2, Naya holds 12 and 47; Raka holds 26 and 80. The correct order is:')}</p><p className="guide-sequence">12 → 26 → 47 → 80</p><p>{t('Naya memainkan 12, Raka 26, Naya 47, lalu Raka 80. Mereka tidak saling menyebutkan angka. Jika kedua kartu terendah justru milik Naya, Naya boleh bermain dua kali berturut-turut.', 'Naya plays 12, Raka 26, Naya 47, and Raka 80. They do not tell each other the numbers. If Naya held both lowest cards instead, she could play twice in a row.')}</p></div>
    </details>

    <details><summary>{t('4. Komunikasi dan timing yang diperbolehkan', '4. Communication and timing')}</summary>
      <p>{t('Kamu menilai sendiri kapan kartu terendahmu layak dimainkan. Angka rendah biasanya terasa lebih awal daripada angka tinggi, tetapi tidak ada rumus detik per angka. Jangan membuat kesepakatan seperti “satu detik berarti satu angka”.', 'Judge for yourself when to play your lowest card. A low number will usually feel earlier than a high one, but there is no seconds-per-number formula. Do not agree on a system such as “one second means one number”.')}</p>
      <p>{t('Jangan memberi tahu angka, rentang, atau petunjuk seperti “punyaku kecil”, “tunggu aku”, dan “kamu dulu”. Emoji, gerakan, ketukan, atau suara yang disepakati untuk menyampaikan isi kartu juga tidak diperbolehkan. Gunakan hanya aksi game yang tersedia untuk siap atau mengusulkan shuriken.', 'Do not reveal numbers, ranges, or hints such as “mine is low”, “wait for me”, or “you go first”. Agreed emojis, gestures, tapping, or sounds that communicate card information are also forbidden. Use the game’s own readiness and shuriken actions.')}</p>
      <p>{t('Jika memakai panggilan suara/video terpisah, tetap patuhi aturan tersebut. Aplikasi tidak menyediakan voice/video, metronom, atau timer bantu. Bunyi game hanya menandai kejadian.', 'If you use a separate voice/video call, follow the same rules. The app has no built-in voice/video, metronome, or timing aid. Game sounds only mark events.')}</p>
    </details>

    <details><summary>{t('5. Salah urutan: satu nyawa hilang', '5. Playing out of order: lose one life')}</summary>
      <p>{t('Kesalahan terjadi jika seseorang memainkan kartu sementara pemain mana pun masih memegang kartu yang lebih rendah. Tim kehilangan satu nyawa untuk kejadian itu, berapa pun jumlah kartu yang terlewat. Semua kartu tangan yang lebih rendah dibuka dan dibuang, termasuk milik pemain offline.', 'A mistake happens when someone plays a card while any player still holds a lower card. The team loses one life for that event, regardless of how many cards were missed. All lower cards still in players’ hands are revealed and discarded, including those held by offline players.')}</p>
      <p className="guide-callout">{t('Kesalahan tidak menaikkan level. Setelah semua pemain siap lagi, kartu untuk level yang sama dibagikan ulang. Kartu pemicu tetap menjadi kartu teratas sampai pembagian baru dimulai.', 'A mistake does not advance the level. Once everyone is ready again, the same level is dealt from a fresh shuffle. The card that caused the mistake stays on top until the new deal begins.')}</p>
      <div className="guide-example"><h4>{t('Contoh beberapa kartu terlewat', 'Several missed cards')}</h4><p>{t('Di level 2: Naya memegang 34, 80; Raka 26, 90; Sinta 12, 35. Naya memainkan 34 terlalu cepat.', 'At level 2: Naya holds 34, 80; Raka 26, 90; Sinta 12, 35. Naya plays 34 too soon.')}</p><ul><li>{t('12 dan 26 dibuka lalu dibuang.', '12 and 26 are revealed and discarded.')}</li><li>{t('Tim kehilangan satu nyawa.', 'The team loses one life.')}</li><li>{t('Kartu 80, 90, dan 35 tidak dilanjutkan.', 'Cards 80, 90, and 35 are not played.')}</li><li>{t('Setelah semua pemain siap, level 2 dibagikan ulang dari dek yang dikocok.', 'Once everyone is ready, level 2 is dealt again from a fresh shuffle.')}</li></ul></div>
      <p>{t('Popup “Urutan kartu salah” menunjukkan kartu terlewat dan nyawa tersisa. Tombol “Lanjut” menutup popup pribadi; setelah itu tekan “Aku siap”. Jika semua kartu sudah habis akibat kesalahan, tim tetap menyelesaikan tahap kesiapan tersebut sebelum masuk hasil level. Jika nyawa sudah nol, yang muncul adalah hasil kalah.', 'The “Card out of order” popup shows missed cards and remaining lives. “Continue” closes your own popup; then press “I’m ready”. If the mistake emptied all hands, the team still completes this readiness step before the level result. If no lives remain, the defeat result is shown instead.')}</p>
    </details>

    <details><summary>{t('6. Shuriken: buang kartu terendah bersama', '6. Shurikens: discard your lowest cards together')}</summary>
      <ol><li>{t('Saat permainan aktif dan shuriken tersedia, seorang pemain menekan “Usulkan shuriken”. Permainan dijeda untuk voting; pengusul langsung dihitung setuju.', 'During active play, if a shuriken is available, a player presses “Suggest shuriken”. Play pauses for a vote; the proposer is counted as approving.')}</li><li>{t('Semua pemain harus setuju, termasuk yang tangannya sudah kosong. Penonton tidak ikut voting. Pemain offline harus kembali untuk menyetujui.', 'Every player must approve, including players with empty hands. Spectators do not vote. Offline players must return to approve.')}</li><li>{t('Jika semuanya setuju, tim memakai satu shuriken. Setiap pemain yang masih memiliki kartu membuka dan membuang satu kartu terendahnya. Tidak ada nyawa yang hilang.', 'If everyone approves, the team spends one shuriken. Each player with cards reveals and discards their single lowest card. No life is lost.')}</li><li>{t('Jika satu pemain menolak, usulan batal dan shuriken tidak terpakai. Setelah voting selesai, semua pemain online menekan “Siap” untuk melanjutkan.', 'If any player declines, the proposal is cancelled and no shuriken is spent. After the vote, all online players press Ready to continue.')}</li></ol>
      <div className="guide-example"><h4>{t('Contoh shuriken disetujui', 'Approved-shuriken example')}</h4><p>{t('Naya memegang 12, 60; Raka 26, 75; Sinta 35, 90. Setelah semua setuju, 12, 26, dan 35 dibuang. Sisa kartu adalah 60, 75, dan 90. Hanya satu shuriken tim yang terpakai, bukan satu per pemain.', 'Naya holds 12, 60; Raka 26, 75; Sinta 35, 90. After everyone approves, 12, 26, and 35 are discarded. The remaining cards are 60, 75, and 90. Only one team shuriken is spent, not one per player.')}</p></div>
      <p>{t('Kartu yang dibuang lewat shuriken diletakkan terpisah, sehingga tidak mengganti kartu teratas tumpukan tengah. Jika tangan seseorang kosong, ia tidak membuang apa pun. Jika shuriken mengosongkan semua tangan, level selesai setelah tim melewati kesiapan berikutnya.', 'Shuriken discards are set aside, so they do not replace the top card of the center pile. A player with an empty hand discards nothing. If the shuriken empties every hand, the level completes after the team’s next readiness step.')}</p>
    </details>

    <details><summary>{t('7. Hadiah dan perpindahan level', '7. Rewards and moving to the next level')}</summary>
      <table><caption>{t('Hadiah diberikan setelah level selesai', 'Rewards are earned after completing a level')}</caption><thead><tr><th scope="col">{t('Level selesai', 'Completed level')}</th><th scope="col">{t('Hadiah tim', 'Team reward')}</th></tr></thead><tbody><tr><td>2, 5, 8</td><td>+1 shuriken</td></tr><tr><td>3, 6, 9</td><td>{t('+1 nyawa', '+1 life')}</td></tr></tbody></table>
      <p>{t('Nyawa maksimal lima dan shuriken maksimal tiga. Hadiah hanya menambah inventori jika masih ada ruang. Tidak ada hadiah di level lain, dan level di atas target jumlah pemain tidak dimainkan.', 'The maximum is five lives and three shurikens. Rewards only add inventory if there is room. Other levels grant no reward, and levels beyond your player-count target are not played.')}</p>
      <div className="guide-example"><h4>{t('Contoh hadiah', 'Reward example')}</h4><p>{t('Tim menyelesaikan level 2 dengan satu shuriken tersisa: persediaan menjadi dua dan popup menunjukkan +1 shuriken. Jika persediaan sudah tiga, tetap tiga. Setelah level 3 selesai dengan dua nyawa, nyawa menjadi tiga.', 'The team completes level 2 with one shuriken remaining: the supply becomes two and the popup shows +1 shuriken. If the supply was already three, it stays three. Completing level 3 with two lives raises the total to three.')}</p></div>
      <p>{t('Popup level selesai menampilkan hasil dan hadiah. Tutup dengan “Lanjut”, lihat kartu level baru, lalu tekan “Siap”. Menutup popup tidak menandai kamu siap dan tidak menutup popup pemain lain. Jumlah kartu per pemain bertambah satu pada level berikutnya.', 'The level-complete popup shows the outcome and reward. Close it with Continue, look at your new hand, then press Ready. Closing the popup does not mark you ready or close anyone else’s popup. Each player gets one more card in the next level.')}</p>
    </details>

    <details><summary>{t('8. Menang, kalah, dan main lagi', '8. Winning, losing, and playing again')}</summary>
      <p>{t('Menang berarti seluruh target level selesai: 12 untuk dua pemain, 10 untuk tiga pemain, atau 8 untuk empat pemain. Kalah berarti tim kehilangan nyawa terakhir. Tidak ada pemenang individual.', 'Winning means completing your final level: 12 for two players, 10 for three, or 8 for four. Losing means the team has spent its last life. There is no individual winner.')}</p>
      <p>{t('Hasil akhir menunjukkan level terakhir, nyawa dan shuriken tersisa, jumlah kesalahan, serta shuriken yang dipakai. Satu kejadian salah urutan dihitung satu kesalahan; voting yang ditolak tidak dihitung sebagai shuriken terpakai. Ringkasan tidak membuka seluruh tangan atau riwayat kartu.', 'The final result shows the last level, remaining lives and shurikens, total mistakes, and shurikens used. One out-of-order event counts as one mistake; a declined vote does not count as a spent shuriken. The summary does not reveal all hands or a card history.')}</p>
      <div className="guide-example"><h4>{t('Contoh nyawa terakhir', 'Last-life example')}</h4><p>{t('Tim hanya punya satu nyawa. Naya memainkan 50 padahal Raka masih memegang 10. Nyawa menjadi nol: tim kalah, meskipun pembuangan kartu 10 membuat semua tangan kosong. Tidak ada hadiah level yang menyelamatkan nyawa terakhir.', 'The team has one life. Naya plays 50 while Raka still holds 10. Lives fall to zero: the team loses, even if discarding 10 empties all hands. A level reward cannot rescue that last life.')}</p></div>
      <p>{t('Host dapat memilih “Kembali ke lobi”. Di lobi, penonton bisa mengambil kursi kosong dan host membagikan kartu untuk pertandingan baru. Pertandingan baru dimulai dari level 1 dengan nyawa awal sesuai jumlah pemain, satu shuriken, dan statistik baru.', 'The host can choose Back to lobby. Spectators can take open seats there, and the host deals a new game. A new match starts at level 1 with the starting lives for its player count, one shuriken, and fresh statistics.')}</p>
    </details>

    <details><summary>{t('9. Koneksi terputus, jeda, dan kembali bermain', '9. Disconnects, pauses, and reconnecting')}</summary>
      <p>{t('Di lobi, host memilih “Jeda otomatis” atau “Lanjut sementara”. Jeda otomatis adalah default. Lanjut sementara memberi waktu kembali 30, 60, atau 120 detik (default 60); jika pemain belum kembali, permainan dijeda. Waktu dihitung setelah aplikasi mendeteksi koneksi putus.', 'In the lobby, the host chooses Pause immediately or Continue temporarily. Immediate pause is the default. Temporary continuation allows 30, 60, or 120 seconds to reconnect (60 by default); if the player has not returned, play pauses. The window begins when the app detects the disconnection.')}</p>
      <p>{t('Kartu pemain offline tetap disimpan dan ikut diperhitungkan. Tidak ada bot, pembuangan otomatis, atau kartu yang dimainkan otomatis untuk menggantikannya. Host boleh melanjutkan dari jeda setelah menerima peringatan risiko; pemain online tetap harus siap.', 'Offline players keep their cards, and those cards still count. No bot, automatic discard, or automatic play replaces them. The host can resume from a pause after acknowledging the risk; online players still need to get ready.')}</p>
      <div className="guide-example"><h4>{t('Contoh melanjutkan tanpa pemain offline', 'Continuing with an offline player')}</h4><p>{t('Raka terputus sambil memegang 18. Host melanjutkan dan Naya memainkan 30. Kartu 18 tetap dianggap terlewat: tim kehilangan satu nyawa dan 18 dibuang. Unpause tidak mengabaikan kartu offline.', 'Raka disconnects holding 18. The host resumes and Naya plays 30. The 18 still counts as missed: the team loses one life and 18 is discarded. Resuming does not ignore offline cards.')}</p></div>
      <p>{t('Pemain yang kembali mendapat sisa kartu dan progres terkini, bukan pembagian baru. Reconnect saat bermain aktif meminta kesiapan ulang. Jika semua pemain offline, permainan tidak dapat berjalan. Dalam voting shuriken, pemain offline tetap wajib kembali untuk menyetujui; host tidak bisa melewati syarat itu.', 'Returning players receive their remaining cards and current progress, not a new deal. Reconnecting during active play triggers readiness again. Play cannot continue when all players are offline. During a shuriken vote, offline players must still return to approve; the host cannot bypass that requirement.')}</p>
    </details>

    <details><summary>{t('10. Host, penonton, dan keluar room', '10. Hosts, spectators, and leaving')}</summary>
      <p>{t('Jika host terputus, kendali berpindah ke pemain online yang paling awal bergabung. Host lama yang kembali menjadi pemain biasa. Penonton tidak otomatis menjadi host. Jika semua pemain terputus, kendali diberikan kepada pemain yang kembali terlebih dahulu.', 'If the host disconnects, control passes to the online player who joined earliest. The old host returns as a regular player. Spectators do not automatically become hosts. If all players disconnected, the first returning player receives control.')}</p>
      <p>{t('Penonton melihat status meja dan jumlah kartu, tetapi tidak melihat angka kartu tangan, melakukan voting, atau memainkan kartu. Popup hasil khusus pemain; penonton mengikuti status meja. Di lobi, gunakan “Ikut bermain” jika ada kursi kosong, atau “Jadi penonton” untuk melepas kursimu.', 'Spectators see table status and card counts, but cannot see hand values, vote, or play. Result popups are for players; spectators follow the table status. In the lobby, use Take a seat if one is available, or Watch instead to give up your seat.')}</p>
      <p>{t('Host boleh mengeluarkan peserta. Jika pemain aktif dikeluarkan atau memilih “Keluar room”, pertandingan dibatalkan dan peserta lain kembali ke lobi. Mengeluarkan penonton tidak membatalkan pertandingan. Host juga bisa mengakhiri pertandingan jika tim tidak dapat melanjutkan.', 'The host may remove participants. If an active player is removed or chooses Leave room, the match is cancelled and the remaining participants return to the lobby. Removing a spectator does not cancel the game. The host can also end a match if the team cannot continue.')}</p>
      <p className="guide-callout">{t('Refresh atau koneksi putus berarti sementara offline. “Keluar room” berarti meninggalkan pertandingan. Gunakan pilihan itu dengan hati-hati saat masih menjadi pemain.', 'Refreshing or losing connection makes you temporarily offline. Leave room means leaving the match. Use it carefully while you are a player.')}</p>
    </details>

    <details><summary>{t('11. Sesi, undangan, bahasa, dan suara', '11. Sessions, invitations, language, and sound')}</summary>
      <ul>
        <li>{t('Refresh di browser yang sama dapat memulihkan sesi selama data sesi browser masih ada. Username saja tidak cukup untuk mengambil alih kartu; browser atau perangkat lain tidak otomatis menjadi sesi yang sama.', 'Refreshing in the same browser can restore your session while its saved session data remains. A nickname alone cannot take over a hand; another browser or device is not automatically the same session.')}</li>
        <li>{t('Jika sesi yang sama dibuka di dua tab, koneksi terbaru mengambil alih dan tab lama dinonaktifkan. Untuk mencoba dua pemain sendiri, gunakan dua profil browser terpisah.', 'If the same session opens in two tabs, the newer connection takes over and the old tab is disabled. To test two players yourself, use separate browser profiles.')}</li>
        <li>{t('Room kedaluwarsa 24 jam setelah pemain terakhir offline/keluar. Penonton tidak memperpanjangnya. Pemain yang kembali sebelum kedaluwarsa membatalkan hitungan tersebut.', 'Rooms expire 24 hours after the last player goes offline or leaves. Spectators do not extend this. A player returning before expiry cancels that countdown.')}</li>
        <li>{t('Ikon mata menyembunyikan atau menampilkan kode di toolbar room. “Salin undangan” tetap menyalin tautan asli. Ini hanya menyamarkan tampilan kode, bukan mengubah akses room atau menyembunyikan URL browser.', 'The eye icon hides or shows the code in the room toolbar. Copy invite still copies the actual link. This only masks the displayed code; it does not change room access or hide the browser URL.')}</li>
        <li>{t('ID/EN mengganti bahasa hanya untukmu. Ikon speaker mengaktifkan atau membisukan efek suara, bukan lagu latar. Pilihan bahasa, suara, dan tampilan kode disimpan di browser.', 'ID/EN changes only your language. The speaker enables or mutes sound effects, not background music. Language, sound, and code-visibility preferences are saved in the browser.')}</li>
        <li>{t('Membuka panduan tidak menjeda permainan dan tidak menandai siap. Sebaiknya baca sebelum mulai atau ketika permainan sudah dijeda.', 'Opening this guide does not pause the game or mark you ready. Read it before starting or while play is already paused.')}</li>
      </ul>
    </details>

    <details><summary>{t('12. Kasus yang sering membingungkan', '12. Common questions')}</summary>
      <h4>{t('Apakah harus mulai dari kartu 1?', 'Do we have to start with 1?')}</h4><p>{t('Tidak. Mulailah dari kartu terendah yang dibagikan. Jika tangan seluruh tim hanya 17, 34, dan 68, urutannya cukup 17 → 34 → 68. Angka yang tidak dibagikan boleh dilompati.', 'No. Start with the lowest dealt card. If the team only holds 17, 34, and 68, the sequence is 17 → 34 → 68. Numbers that were not dealt can be skipped.')}</p>
      <h4>{t('Dua pemain menekan kartu hampir bersamaan?', 'What if two players click almost simultaneously?')}</h4><p>{t('Urutan mengikuti aksi yang lebih dahulu diterima server. Sistem tidak mengurutkan angka otomatis agar selamat. Perbedaan jaringan dapat memengaruhi aksi yang sangat berdekatan.', 'Actions are ordered by when the server receives them. The system does not sort numbers automatically to save the team. Network differences can affect very close actions.')}</p>
      <h4>{t('Mengapa kartu tidak bisa ditekan?', 'Why can’t I play a card?')}</h4><p>{t('Pastikan kamu pemain, terhubung, permainan sudah aktif, tidak sedang menunggu hasil aksi sebelumnya, dan kartu itu adalah yang terendah di tanganmu. Saat voting, jeda, atau kesiapan, kartu tidak bisa dimainkan.', 'Make sure you are a player, connected, play is active, no previous action is pending, and the card is your lowest. Cards cannot be played during voting, pauses, or readiness.')}</p>
      <h4>{t('Mengapa shuriken belum dipakai meski aku setuju?', 'Why hasn’t the shuriken been used after I approved?')}</h4><p>{t('Semua pemain harus setuju. Periksa siapa yang belum menyetujui atau sedang offline. Jika seseorang menolak, inventori shuriken tetap utuh.', 'Every player must approve. Check who has not approved or is offline. If someone declines, the shuriken inventory stays unchanged.')}</p>
      <h4>{t('Apakah ini mencakup semua varian original?', 'Does this include every original variant?')}</h4><p>{t('Saat ini tersedia mode standar dengan penyesuaian online yang dijelaskan di atas. Tombol fokus ulang bebas tidak tersedia. Blind Mode setelah kemenangan belum diimplementasikan; permainan berikutnya adalah rematch normal.', 'Currently, the standard mode is available with the online adjustments described above. There is no unrestricted refocus button. The post-victory Blind Mode is not implemented; the next game is a normal rematch.')}</p>
    </details>
  </div>;
}
